### ISSUE TITLE
Performance test V1.0.6 beta: using list_content not faster

### ISSUE THREAD

**Issue by guwirth** [etas/vs-boost-unit-test-adapter#53]
Did a first performance test of V1.0.6 with a big solution. The current version is slightly slower. Wondering because after closing #24 and #26 it should be faster now. For testing we were using the solution HWAccessBoostTests.sln.

**Comment by netspiri** [comment]
Pull request #57 should address some of these issues. Could you kindly confirm if performance for said solution is better?

**Comment by guwirth** [comment]
Test with #57 :-1:

**Comment by netspiri** [comment]
@guwirth Is this issue resolved at this point?

**Comment by guwirth** [comment]
It's on the same level now so the issue could normally be closed. But I still don't understand why asking the exe is not faster than parsing all source files?

Did you try to profile the plugin to find the bottleneck?

**Comment by guwirth** [comment]
As far as I understand plugin is doing the following steps:
* loading PDB file to verify if exe is a boost unit test runner: in our context these files are very big, containing symbols from MFC, ATL, STL and Boost
* starting the exe to get help and see if list_content is supported
* starting the exe with list_content to get the list of unit tests
  * our exe files are also very big because most other parts are statically linked

To speed up things there should be a solution working without the PDBs and starting the exe only once. 

@raffienficiaud Do you have an idea?
